image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv
    - .tox

before_script:
  - python3 --version
  - python3 -m pip install tox

test:
  stage: test
  script:
    - tox

docs:
  stage: test
  script:
    - tox -e docs

pages:
  only:
    - master
  stage: deploy
  script:
    - tox -e docs
  artifacts:
    paths:
      - public
